# -d "text=❌ ${{ github.workflow }} #${{ github.run_number }}
# ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
# Commit: ${{ github.sha }}
# Por: ${{ github.actor }}"

# -d "text=✅ ${{ github.workflow }} #${{ github.run_number }}
# ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
# Commit: ${{ github.sha }}
# Por: ${{ github.actor }}"

name: Teste Samir

on:
  push:
    branches:
    - main

jobs:
  push-and-deploy:
    runs-on: ubuntu-latest
    name: Docker build and push to ECR
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Notify Telegram Setup Message
        run: echo "BO_TELEGRAM_MESSAGE="${{ vars.BO_TELEGRAM_WORKFLOW_MESSAGE }}"" >> $GITHUB_ENV

      - name: Notify Success Telegram
        run: |
          echo "execute curl with message '✅ ${{ env.BO_TELEGRAM_MESSAGE }}'"

      - name: Notify Failure Telegram
        if: failure()
        run: |
          echo "execute curl with message '❌ ${{ env.BO_TELEGRAM_MESSAGE }}'"
